# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      language_version: python3.6
      additional_dependencies:
        - flake8-bugbear

-   repo: https://github.com/Eandrju/hooks
    rev: v0.1
    hooks:
    - id: jira-commit-msg-validation

